Reworded sentences for clarity
hirosystems/stacks.js-starters pull request #3
Opened 2022-07-14 23:10 UTC by LakshmiLavanyaKasturi

- Reworded and changed tense in a sentence.
- Added clarity by rearranging words.

2022-07-15 16:43 UTC, LakshmiLavanyaKasturi commented
Relates to https://github.com/hirosystems/docs/issues/120

2022-07-15 19:35 UTC, janniks commented on README.md
> +The [`npm init`](https://docs.npmjs.com/cli/v8/commands/npm-init) and it's alias `npm create` can be seen as an alias for `npm exec create-<...>`.
This one should be a possessive `its`, right?

2022-07-15 20:35 UTC, sabbyanandan requested changes

2022-07-15 20:35 UTC, sabbyanandan commented on README.md
>  ## Quick-Start a Stacks.js Project
Could we add an intro/overview paragraph to describe this repo's intent or objective? Explaining that first and getting into the usage steps next would be helpful.

IMHO, this project aims to help quickly bootstrap frontend applications with Stacks.js on top of the desired JS framework as the foundation.

2022-07-18 18:36 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan Looks good?

2022-07-18 18:40 UTC, sabbyanandan requested changes

2022-07-18 18:40 UTC, sabbyanandan commented on README.md
> +This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the desired JS framework as the foundation.
Perhaps move this to the top and above the template bullets? So folks know right away what this project is about.

2022-07-18 18:40 UTC, sabbyanandan commented on README.md
> +This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the desired JS framework as the foundation.
```suggestion
This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the following JS frameworks as the foundation.
```

2022-07-18 18:41 UTC, sabbyanandan commented on README.md
> +This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the desired JS framework as the foundation.
This statement would be true if we move this description to the top.

2022-07-18 18:41 UTC, sabbyanandan commented on README.md
> +This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the desired JS framework as the foundation.
Maybe also expand JS = Javascript

2022-07-18 20:54 UTC, sabbyanandan approved these changes
@LakshmiLavanyaKasturi: Thanks!

2022-07-18 22:26 UTC, LakshmiLavanyaKasturi commented
@janniks: Can I get write permissions to [Stacks.js-starters](https://github.com/hirosystems/stacks.js-starters) repo?

2022-07-19 14:07 UTC, janniks commented
> @janniks: Can I get write permissions to [Stacks.js-starters](https://github.com/hirosystems/stacks.js-starters) repo?

Done ✅

2022-07-19 14:17 UTC, janniks commented on README.md
> +This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the following Javascript frameworks as the foundation.
```suggestion
This project aims to help quickly bootstrap frontend applications with Stacks.js on top of the following JavaScript frameworks as the foundation.
```

2022-07-19 14:17 UTC, janniks approved these changes

2022-07-20 19:41 UTC, merged